### ISSUE TITLE
Mono.then(lambda) is giving compilation error

### ISSUE THREAD

**Issue by sivaprasadreddy** [reactor/reactor-core#539]
I have a **SpringBoot WebFlux** application using **reactor-core**.

The following code is working fine with **reactor-core-3.0.6.RELEASE.jar**.

```
public Mono<Void> savePerson(Mono<Person> personMono) {
		return personMono.then(person -> {
			int id = people.size() + 1;
			people.put(id, person);
			System.out.format("Saved %s with id %d%n", person, id);
			return Mono.empty();
		});
	}
```
But when I update the reactor-core version to **3.1.0-BUILD-SNAPSHOT** it is giving the compilation error: 

`The method then(Mono<V>) in the type Mono<Person> is not applicable for the arguments ((<no type> person) -> {})`

Any help would be appreciated?

**Comment by bijukunjummen** [comment]
I hit the same scenario today @sivaprasadreddy, I think this commit https://github.com/reactor/reactor-core/commit/d7378c539e3be18fbe0b424397b9681420520a0a replaces `then` with `flatMap`(a good call IMHO). Replacing your call with `flatMap` should fix it for you.

**Comment by simonbasle** [comment]
@sivaprasadreddy @bijukunjummen that is correct. Reactor 3.1 will be the LTS branch that will back Spring 5.x, so we are taking our last chances to polish the API into something that users can be happy with for the next few years at least 😄 

As a consequence, there will be API changes from 3.0.x to 3.1.0. Another example is #535. We tried to lay out a migration path in 3.0.x branch by deprecating these changing methods, documenting how it will change in their javadoc and introducing the alternatives early where possible.

That `then` change wasn't in 3.0.6.RELEASE but there will be a 3.0.7.RELEASE where the deprecation occurs.

You can have a look at #323 too, where we _try_ to track most of these deprecations that are slated for removal in 3.1.0.
